name: I2-PERF::GENESIS

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [feature/DOPS-3319/genesis-external]

jobs:
  genesis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    #   - name: copy file via ssh key
    #     uses: appleboy/scp-action@master
    #     with:
    #       host: ${{ secrets.HOST }}
    #       username: ${{ secrets.USERNAME }}
    #       port: ${{ secrets.PORT }}
    #       key: ${{ secrets.KEY }}
    #       source: src/test/resources/iroha2_config/genesis.json
    #       target: /opt
    #       strip_components: 4
          #overwrite: true
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: src/test/resources/iroha2_config/genesis.json
          remote_path: /opt
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
