name: I2-PERF::GENESIS

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [feature/DOPS-3319/genesis-external]

jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - name: Copy to Remote Server
        uses: pierrickdelrieu/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          ssh_port: ${{ secrets.PORT }}
          ssh_username: ${{ secrets.USERNAME }}
          ssh_key: ${{ secrets.KEY }}
          source_dir: src/test/resources/iroha2_config
          destination_dir: /home/vzyabkin/docker-share-files
